export const SET_ADDRESS = "SET_ADDRESS";
export const SET_BALANCE = "SET_BALANCE";
export const SET_TOTAL_FLOOR = "SET_TOTAL_FLOOR";
export const SET_TOTAL_BALANCE_ETH = "SET_TOTAL_BALANCE_ETH";
export const SET_TOTAL_BALANCE_USD = "SET_TOTAL_BALANCE_USD";
export const SET_DAILY_EXPENDITURE = "SET_DAILY_EXPENDITURE";
export const SET_DAILY_INCOME = "SET_DAILY_INCOME";
export const SET_DAILY_PROFIT = "SET_DAILY_PROFIT";
